# Generated by Django 5.1 on 2024-09-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('O', 'Oil Change'), ('T', 'Tire Rotation'), ('B', 'Brake Repair'), ('E', 'Engine turn-up'), ('W', 'Wheel Alignment'), ('A', 'Air Conditioning  Service'), ('D', 'Detailing'), ('S', 'Suspension Repair')], default='O', max_length=1),
        ),
    ]
